<?php

namespace App\Http\Controllers;

use App\Models\Location;
use App\Models\Company;
use App\Models\Employee;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Inertia\Inertia;
use Inertia\Response;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\JsonResponse;

class LocationController extends Controller
{
    private function accessibleCompanyIds($user)
    {
        $ids = $user->ownedCompanies()->pluck('id');

        if ($ids->isEmpty()) {
            $employeeCompanyId = Employee::query()
                ->where('user_id', $user->id)
                ->value('company_id');

            if ($employeeCompanyId) {
                $ids = collect([$employeeCompanyId]);
            }
        }

        return $ids;
    }

    private function accessibleCompanies($user)
    {
        $ids = $this->accessibleCompanyIds($user);

        return Company::query()->whereIn('id', $ids)->get();
    }

    /**
     * Display a listing of the locations.
     */
    public function index(): Response|RedirectResponse
    {
        $user = Auth::user();
        $companies = $this->accessibleCompanies($user);
        $ownedCompanyIds = $companies->pluck('id');
        
        // If user doesn't have any companies, redirect to create one
        if ($ownedCompanyIds->isEmpty()) {
            return redirect()->route('companies.create')
                ->with('info', 'Please create a company first to manage locations.');
        }
        
        $locations = Location::whereIn('company_id', $ownedCompanyIds)
            ->with(['company', 'assets'])
            ->withCount(['assets'])
            ->latest()
            ->paginate(12);

        return Inertia::render('Locations/Index', [
            'locations' => $locations,
            'companies' => $companies,
            'currentCompany' => $user->currentCompany(),
        ]);
    }

    /**
     * Show the form for creating a new location.
     */
    public function create(): Response|RedirectResponse
    {
        $user = Auth::user();
        $companies = $this->accessibleCompanies($user);
        
        // If user doesn't have any companies, redirect to create one
        if ($companies->isEmpty()) {
            return redirect()->route('companies.create')
                ->with('info', 'Please create a company first to manage locations.');
        }

        return Inertia::render('Locations/Create', [
            'companies' => $companies,
            'currentCompany' => $user->currentCompany(),
        ]);
    }

    /**
     * Store a newly created location in storage.
     */
    public function store(Request $request): RedirectResponse|JsonResponse
    {
        $user = Auth::user();
        
        $validated = $request->validate([
            'company_id' => 'required|exists:companies,id',
            'name' => 'required|string|max:255',
            'building' => 'nullable|string|max:100',
            'office_number' => 'nullable|string|max:50',
            'address' => 'nullable|string|max:255',
            'city' => 'nullable|string|max:100',
            'state' => 'nullable|string|max:100',
            'postal_code' => 'nullable|string|max:20',
            'country' => 'nullable|string|max:100',
        ]);

        // Verify user owns the selected company
        abort_unless($this->accessibleCompanyIds($user)->contains((int) $validated['company_id']), 403);

        // Code will be auto-generated by the model
        $location = Location::create($validated);

        // If this is an AJAX request (from assets wizard/modal), return JSON
        if ($request->wantsJson() || $request->has('_from_modal')) {
            return response()->json([
                'success' => true,
                'location' => $location->load('company'),
                'message' => 'Location created successfully.',
            ]);
        }

        return redirect()->route('locations.show', $location)
            ->with('success', 'Location created successfully.');
    }

    /**
     * Display the specified location.
     */
    public function show(Location $location): Response|RedirectResponse
    {
        $user = Auth::user();
        $ownedCompanyIds = $this->accessibleCompanyIds($user);
        
        // If user doesn't have any companies, redirect to create one
        if ($ownedCompanyIds->isEmpty()) {
            return redirect()->route('companies.create')
                ->with('info', 'Please create a company first to manage locations.');
        }
        
        // Check if user has access to this location
        if (!$ownedCompanyIds->contains($location->company_id)) {
            abort(403);
        }

        $location->load(['company', 'assets.assetCategory']);
        $location->loadCount(['assets']);

        return Inertia::render('Locations/Show', [
            'location' => $location,
        ]);
    }

    /**
     * Show the form for editing the specified location.
     */
    public function edit(Location $location): Response|RedirectResponse
    {
        $user = Auth::user();
        $ownedCompanyIds = $this->accessibleCompanyIds($user);
        
        // If user doesn't have any companies, redirect to create one
        if ($ownedCompanyIds->isEmpty()) {
            return redirect()->route('companies.create')
                ->with('info', 'Please create a company first to manage locations.');
        }
        
        // Check if user has access to this location
        if (!$ownedCompanyIds->contains($location->company_id)) {
            abort(403);
        }

        $companies = $this->accessibleCompanies($user);

        return Inertia::render('Locations/Edit', [
            'location' => $location,
            'companies' => $companies,
        ]);
    }

    /**
     * Update the specified location in storage.
     */
    public function update(Request $request, Location $location): RedirectResponse
    {
        $user = Auth::user();
        $ownedCompanyIds = $this->accessibleCompanyIds($user);
        
        // If user doesn't have any companies, redirect to create one
        if ($ownedCompanyIds->isEmpty()) {
            return redirect()->route('companies.create')
                ->with('info', 'Please create a company first to manage locations.');
        }
        
        // Check if user has access to this location
        if (!$ownedCompanyIds->contains($location->company_id)) {
            abort(403);
        }

        $validated = $request->validate([
            'company_id' => 'required|exists:companies,id',
            'name' => 'required|string|max:255',
            'building' => 'nullable|string|max:100',
            'office_number' => 'nullable|string|max:50',
            'address' => 'nullable|string|max:255',
            'city' => 'nullable|string|max:100',
            'state' => 'nullable|string|max:100',
            'postal_code' => 'nullable|string|max:20',
            'country' => 'nullable|string|max:100',
        ]);

        // Verify user owns the selected company (in case they're changing it)
        abort_unless($ownedCompanyIds->contains((int) $validated['company_id']), 403);

        $location->update($validated);

        return redirect()->route('locations.show', $location)
            ->with('success', 'Location updated successfully.');
    }

    /**
     * Remove the specified location from storage.
     */
    public function destroy(Location $location): RedirectResponse
    {
        $user = Auth::user();
        $ownedCompanyIds = $this->accessibleCompanyIds($user);
        
        // If user doesn't have any companies, redirect to create one
        if ($ownedCompanyIds->isEmpty()) {
            return redirect()->route('companies.create')
                ->with('info', 'Please create a company first to manage locations.');
        }
        
        // Check if user has access to this location
        if (!$ownedCompanyIds->contains($location->company_id)) {
            abort(403);
        }

        // Check if location has assets
        if ($location->assets()->count() > 0) {
            return redirect()->route('locations.index')
                ->with('error', 'Cannot delete location that has assets assigned.');
        }

        $location->delete();

        return redirect()->route('locations.index')
            ->with('success', 'Location deleted successfully.');
    }

    /**
     * Search locations for async selection.
     */
    public function search(Request $request)
    {
        $user = Auth::user();
        $accessibleCompanyIds = $this->accessibleCompanyIds($user);
        $query = $request->get('q', '');
        $companyId = $request->get('company_id');
        
        $locations = Location::query()
            ->whereIn('company_id', $accessibleCompanyIds)
            ->when($companyId, function ($q) use ($companyId) {
                return $q->where('company_id', $companyId);
            })
            ->when($query, function ($q) use ($query) {
                return $q->where(function ($subQuery) use ($query) {
                    $subQuery->where('name', 'like', "%{$query}%")
                        ->orWhere('code', 'like', "%{$query}%")
                        ->orWhere('building', 'like', "%{$query}%")
                        ->orWhere('office_number', 'like', "%{$query}%")
                        ->orWhere('address', 'like', "%{$query}%")
                        ->orWhere('city', 'like', "%{$query}%");
                });
            })
            ->with('company')
            ->orderBy('name')
            ->limit(20)
            ->get()
            ->map(function ($location) {
                return [
                    'id' => $location->id,
                    'name' => $location->name,
                    'code' => $location->code,
                    'building' => $location->building,
                    'office_number' => $location->office_number,
                    'address' => $location->address,
                    'city' => $location->city,
                    'company_name' => $location->company->name_en,
                    'display_name' => "{$location->code}: {$location->name}" . 
                        ($location->building ? " - Building {$location->building}" : '') .
                        ($location->office_number ? " - Office {$location->office_number}" : ''),
                    'full_address' => collect([
                        $location->address,
                        $location->city,
                        $location->state,
                        $location->country
                    ])->filter()->join(', ')
                ];
            });

        return response()->json($locations);
    }
}
